language: cpp
compiler:
  - gcc
  - clang

script: 
  - g++ -O3 -I /usr/local/boost_1_54_0 *.cpp -o trimax 
  
addons:
  apt:
    packages:
    - g++-multilib
    - libboost1.54.0
    - libboost1.54.0-all
    - libboost1.54.0-all-dev