language: cpp
compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev
  
script: 
  - g++ -O3  *.cpp -o trimax 
  
addons:
  apt:
    packages:
    - g++-multilib